import { FileText, Users, Shield, AlertTriangle } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

export default function TermsOfServicePage() {
	return (
		<div className='min-h-screen bg-gradient-to-br from-blue-50 via-indigo-50 to-purple-50 py-12'>
			<div className='container mx-auto px-4 max-w-4xl'>
				<div className='text-center mb-12'>
					<h1 className='text-4xl md:text-5xl font-bold text-gray-800 mb-4'>
						Terms of Service
					</h1>
					<p className='text-xl text-gray-600 max-w-2xl mx-auto'>
						Please read these terms carefully before using our
						services
					</p>
					<p className='text-sm text-gray-500 mt-4'>
						Last updated: January 2024
					</p>
				</div>

				<div className='space-y-8'>
					<Card className='border-0 shadow-xl bg-white/80 backdrop-blur-sm'>
						<CardHeader>
							<div className='w-12 h-12 bg-gradient-to-r from-blue-500 to-indigo-600 rounded-full flex items-center justify-center mb-4'>
								<FileText className='w-6 h-6 text-white' />
							</div>
							<CardTitle>Acceptance of Terms</CardTitle>
						</CardHeader>
						<CardContent>
							<p className='text-gray-600 leading-relaxed'>
								By accessing and using ToolBox Pro
								(&quot;Service&quot;), you accept and agree to
								be bound by the terms and provision of this
								agreement. If you do not agree to abide by the
								above, please do not use this service.
							</p>
						</CardContent>
					</Card>

					<Card className='border-0 shadow-xl bg-white/80 backdrop-blur-sm'>
						<CardHeader>
							<div className='w-12 h-12 bg-gradient-to-r from-purple-500 to-pink-600 rounded-full flex items-center justify-center mb-4'>
								<Users className='w-6 h-6 text-white' />
							</div>
							<CardTitle>Use License</CardTitle>
						</CardHeader>
						<CardContent className='space-y-4'>
							<div>
								<h3 className='font-semibold text-gray-800 mb-2'>
									Permission is granted to:
								</h3>
								<ul className='list-disc list-inside text-gray-600 space-y-1'>
									<li>
										Use our tools for personal and
										commercial purposes
									</li>
									<li>
										Access and use the service in accordance
										with these terms
									</li>
									<li>
										Share results generated by our tools
									</li>
								</ul>
							</div>
							<div>
								<h3 className='font-semibold text-gray-800 mb-2'>
									This license shall automatically terminate
									if you:
								</h3>
								<ul className='list-disc list-inside text-gray-600 space-y-1'>
									<li>Violate any of these restrictions</li>
									<li>
										Use the service for illegal purposes
									</li>
									<li>
										Attempt to reverse engineer or copy our
										tools
									</li>
								</ul>
							</div>
						</CardContent>
					</Card>

					<Card className='border-0 shadow-xl bg-white/80 backdrop-blur-sm'>
						<CardHeader>
							<div className='w-12 h-12 bg-gradient-to-r from-green-500 to-teal-600 rounded-full flex items-center justify-center mb-4'>
								<Shield className='w-6 h-6 text-white' />
							</div>
							<CardTitle>Acceptable Use Policy</CardTitle>
						</CardHeader>
						<CardContent className='space-y-4'>
							<div>
								<h3 className='font-semibold text-gray-800 mb-2'>
									You agree NOT to use the service to:
								</h3>
								<ul className='list-disc list-inside text-gray-600 space-y-1'>
									<li>
										Violate any applicable laws or
										regulations
									</li>
									<li>
										Infringe on intellectual property rights
									</li>
									<li>
										Transmit harmful, offensive, or
										inappropriate content
									</li>
									<li>
										Attempt to gain unauthorized access to
										our systems
									</li>
									<li>
										Interfere with or disrupt the service
									</li>
									<li>
										Use automated tools to access the
										service excessively
									</li>
								</ul>
							</div>
							<div>
								<h3 className='font-semibold text-gray-800 mb-2'>
									Content Guidelines:
								</h3>
								<p className='text-gray-600'>
									While we don&apos;t monitor the content you
									input into our tools, you are responsible
									for ensuring that your use complies with all
									applicable laws and does not infringe on
									third-party rights.
								</p>
							</div>
						</CardContent>
					</Card>

					<Card className='border-0 shadow-xl bg-white/80 backdrop-blur-sm'>
						<CardHeader>
							<CardTitle>Service Availability</CardTitle>
						</CardHeader>
						<CardContent className='space-y-4'>
							<div>
								<h3 className='font-semibold text-gray-800 mb-2'>
									Service Provision:
								</h3>
								<ul className='list-disc list-inside text-gray-600 space-y-1'>
									<li>
										We strive to maintain 99.9% uptime but
										cannot guarantee uninterrupted service
									</li>
									<li>
										We may temporarily suspend service for
										maintenance or updates
									</li>
									<li>
										We reserve the right to modify or
										discontinue the service at any time
									</li>
									<li>
										Free services are provided
										&quot;as-is&quot; without warranties
									</li>
								</ul>
							</div>
							<div>
								<h3 className='font-semibold text-gray-800 mb-2'>
									User Responsibilities:
								</h3>
								<p className='text-gray-600'>
									You are responsible for maintaining your own
									backups of any important data and for
									ensuring your internet connection and device
									compatibility.
								</p>
							</div>
						</CardContent>
					</Card>

					<Card className='border-0 shadow-xl bg-white/80 backdrop-blur-sm'>
						<CardHeader>
							<div className='w-12 h-12 bg-gradient-to-r from-orange-500 to-red-600 rounded-full flex items-center justify-center mb-4'>
								<AlertTriangle className='w-6 h-6 text-white' />
							</div>
							<CardTitle>Disclaimers & Limitations</CardTitle>
						</CardHeader>
						<CardContent className='space-y-4'>
							<div>
								<h3 className='font-semibold text-gray-800 mb-2'>
									Service Disclaimers:
								</h3>
								<ul className='list-disc list-inside text-gray-600 space-y-1'>
									<li>
										The service is provided &quot;as
										is&quot; without any warranties
									</li>
									<li>
										We do not guarantee the accuracy of
										results from our tools
									</li>
									<li>
										We are not responsible for decisions
										made based on tool outputs
									</li>
									<li>
										Third-party API dependencies may affect
										service availability
									</li>
								</ul>
							</div>
							<div>
								<h3 className='font-semibold text-gray-800 mb-2'>
									Limitation of Liability:
								</h3>
								<p className='text-gray-600'>
									In no event shall ToolBox Pro be liable for
									any indirect, incidental, special,
									consequential, or punitive damages,
									including without limitation, loss of
									profits, data, use, goodwill, or other
									intangible losses.
								</p>
							</div>
						</CardContent>
					</Card>

					<Card className='border-0 shadow-xl bg-white/80 backdrop-blur-sm'>
						<CardHeader>
							<CardTitle>Intellectual Property</CardTitle>
						</CardHeader>
						<CardContent className='space-y-4'>
							<div>
								<h3 className='font-semibold text-gray-800 mb-2'>
									Our Rights:
								</h3>
								<ul className='list-disc list-inside text-gray-600 space-y-1'>
									<li>
										ToolBox Pro and its original content are
										protected by copyright and trademark
										laws
									</li>
									<li>
										Our tools, algorithms, and user
										interface are proprietary
									</li>
									<li>
										You may not reproduce, distribute, or
										create derivative works without
										permission
									</li>
								</ul>
							</div>
							<div>
								<h3 className='font-semibold text-gray-800 mb-2'>
									Your Rights:
								</h3>
								<p className='text-gray-600'>
									You retain all rights to the content you
									input into our tools. We do not claim
									ownership of your data or the results
									generated by our tools.
								</p>
							</div>
						</CardContent>
					</Card>

					<Card className='border-0 shadow-xl bg-white/80 backdrop-blur-sm'>
						<CardHeader>
							<CardTitle>Privacy & Data</CardTitle>
						</CardHeader>
						<CardContent>
							<p className='text-gray-600 leading-relaxed'>
								Your privacy is important to us. Our collection
								and use of personal information is governed by
								our Privacy Policy, which is incorporated into
								these Terms by reference. By using our service,
								you consent to the collection and use of
								information as outlined in our Privacy Policy.
							</p>
						</CardContent>
					</Card>

					<Card className='border-0 shadow-xl bg-white/80 backdrop-blur-sm'>
						<CardHeader>
							<CardTitle>Termination</CardTitle>
						</CardHeader>
						<CardContent className='space-y-4'>
							<div>
								<h3 className='font-semibold text-gray-800 mb-2'>
									We may terminate your access if:
								</h3>
								<ul className='list-disc list-inside text-gray-600 space-y-1'>
									<li>You violate these Terms of Service</li>
									<li>
										You use the service for illegal
										activities
									</li>
									<li>You abuse or overload our systems</li>
									<li>We discontinue the service</li>
								</ul>
							</div>
							<p className='text-gray-600'>
								You may stop using our service at any time. Upon
								termination, your right to use the service will
								cease immediately.
							</p>
						</CardContent>
					</Card>

					<Card className='border-0 shadow-xl bg-white/80 backdrop-blur-sm'>
						<CardHeader>
							<CardTitle>Changes to Terms</CardTitle>
						</CardHeader>
						<CardContent>
							<p className='text-gray-600 leading-relaxed'>
								We reserve the right to modify these terms at
								any time. We will notify users of any material
								changes by posting the updated terms on this
								page and updating the &quot;Last updated&quot;
								date. Your continued use of the service after
								changes constitutes acceptance of the new terms.
							</p>
						</CardContent>
					</Card>

					<Card className='border-0 shadow-xl bg-white/80 backdrop-blur-sm'>
						<CardHeader>
							<CardTitle>Governing Law</CardTitle>
						</CardHeader>
						<CardContent>
							<p className='text-gray-600 leading-relaxed'>
								These Terms shall be interpreted and governed in
								accordance with the laws of the State of
								California, United States, without regard to its
								conflict of law provisions. Any disputes arising
								from these terms will be resolved in the courts
								of San Francisco County, California.
							</p>
						</CardContent>
					</Card>

					<Card className='border-0 shadow-xl bg-white/80 backdrop-blur-sm'>
						<CardHeader>
							<CardTitle>Contact Information</CardTitle>
						</CardHeader>
						<CardContent>
							<p className='text-gray-600 mb-4'>
								If you have any questions about these Terms of
								Service, please contact us:
							</p>
							<div className='space-y-2 text-gray-600'>
								<p>
									<strong>Email:</strong> toolboxpro@gmail.com
								</p>
								<p>
									<strong>Address:</strong> 123 New Delhi,
									India
								</p>
								<p>
									<strong>Phone:</strong> +91 9876543210
								</p>
							</div>
						</CardContent>
					</Card>

					<Card className='border-0 shadow-xl bg-gradient-to-r from-blue-600 via-purple-600 to-indigo-600 text-white'>
						<CardContent className='p-6'>
							<h3 className='font-semibold mb-2'>Agreement</h3>
							<p className='text-blue-100 text-sm'>
								By using ToolBox Pro, you acknowledge that you
								have read, understood, and agree to be bound by
								these Terms of Service and our Privacy Policy.
							</p>
						</CardContent>
					</Card>
				</div>
			</div>
		</div>
	);
}
